### ISSUE TITLE
 Lean Inception - Kick Off

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#1]
## Descrição da Issue
O Kick-off é a primeira atividade do Lean Inception. Realização de uma reunião inicial com o cliente.

### Tasks: 
- [x] Apresentação dos membros ativos e stakeholder;
- [x] Quebra gelo;
- [x] Apresentação do Lean Inception;
- [x] Apresentação da ideia inicial de produto que será desenvolvido na Lean Inception.

### Critérios de aceitação

- [x] Participação obrigatória do stakeholder;
- [x] Documentação dos participantes da Lean Inception.

**Comment by sudjoao** [comment]
Sobre o Kick-off:
* A plataforma Gather foi utilizada como sala de guerra;
* O cliente apresentou  a ideia do produto;
* O check-in foi feito utilizando a  dinâmica Telefone Visual, utilizando a plataforma Gartic Phone;
* A agenda foi validada pelo cliente, e a participação dele ficou nos 2 primeiros dias do Lean (Dia 04/07/2021 e 05/07/2021)
