### ISSUE TITLE
Lean Inception - Sequenciador

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#10]
## Descrição da Issue
Organizar visualmente a sequência em que as funcionalidades serão realizadas.
### Tasks: 
- [x] Organizar a dinâmica;
- [x] Organizar sequencialmente as ordem da implementação das funcionalidades;
- [x] Definir quais funcionalidades farão parte do MVP;
- [x] Definir os incrementos futuros.

### Critérios de aceitação
- [x] Participação de pelo menos 50% do time;
- [x] Organização seguindo as regras do sequenciador;
- [x] MVP condizente com o objetivo do produto;
- [ ] Validação com o dono do produto.

**Comment by sudjoao** [comment]
Sequenciador:
* MVP
![image](https://user-images.githubusercontent.com/46005310/128863488-4dbec470-74d4-4164-9b4e-26e0f75915d8.png)
* Incremento 1
![image](https://user-images.githubusercontent.com/46005310/128863549-cf6a94e8-04cf-4e46-96ed-f022467f28a7.png)
* Incremento 2
![image](https://user-images.githubusercontent.com/46005310/128863599-c5b1d1f8-064f-4bf4-a425-cb244e41019e.png)
