### ISSUE TITLE
Testes no projeto de flutter

### ISSUE THREAD

**Issue by PhRezende-eng** [fga-eps-mds/2021.1-Pro-Especies-Docs#106]
## Descrição da Issue
Realizar a cobertura de testes no Projeto de Flutter;

### Tasks: 
- [ ] Criar os testes para os métodos/classes do Projeto de Flutter ;

### Critérios de aceitação
- [ ] Todos os testes estarem rodando;
- [ ] Coverage de pelo menos 75%;
