### ISSUE TITLE
Testes no repositório da FishWiki

### ISSUE THREAD

**Issue by gabrielfreitass1** [fga-eps-mds/2021.1-Pro-Especies-Docs#108]
## Descrição da Issue
Realizar cobertura de testes no repositório da FishWiki(biblioteca de peixes);

### Tasks: 
- [x] Criar testes para os métodos do repositório;

### Critérios de aceitação
- [x] Todos os testes estarem rodando;
- [x] Coverage de ao menos 75%;

**Comment by gabrielfreitass1** [comment]
Issue concluída
