### ISSUE TITLE
Configurar codecov nos serviços

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#109]
## Descrição da Issue
Configurar a ferramento CodeCov nos serviços do projeto.
### Tasks: 
- [ ] Fazer a configuração dos testes;
- [ ] Fazer a configuração do codecov;
- [ ] Integrar como CI do GIthub Actions.

### Critérios de aceitação

- [ ] Rodar toda vez que fazer um push/pull request;
- [ ] Salvar dados no codecov.
