### ISSUE TITLE
Criação do Documento de Metodologia

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#11]
## Descrição da Issue
Criação do Documento de Metodologia para as disciplinas de MDS/EPS. Deve conter todas as metodologias que serão usadas durante o semestre. 

### Tasks: 
- [x] Descrever todas as metodologias;
- [x] Colocar no gh-pages.

### Critérios de aceitação

- [x] Estar tudo funcionando dentro do gh-pages;
- [x] Descrever todas as metodologias detalhadas.
