### ISSUE TITLE
Configurar CI para gerar Release

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#110]
## Descrição da Issue
Utilizar o github actions para gerar uma nova tag e uma nova release após um merge na branch master

### Tasks: 
- [ ] Criar o CI para merges na master
- [ ] Gerar uma nova tag
- [ ] Gerar uma nova release a partir da tag

### Critérios de aceitação
- [ ] Todo processo ocorrer de forma automática no CI
