### ISSUE TITLE
Elaborar GQM (Goal Question Metric)

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#111]
## Descrição da Issue
Elaborar o documento de qualidade GQM (*Goal Question Metric*).

### Tasks: 
- [ ] Elaborar o documento a fim de mostrar as métricas de qualidade do produto;
- [ ] Subir para o gh-pages;

### Critérios de aceitação
- [ ] Documento completo com todos os requisitos do GQM;
- [ ] Documento estar disponível no gh-pages.
