### ISSUE TITLE
Criação do repositório e ambiente de configuração de registro de peixes no GitHub

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#112]
## Descrição da Issue
Será necessário a criação e configuração do ambiente de desenvolvimento do serviço de registros, afim que o time possa ter mais conforto no desenvolvimento. Além de posteriormente serem utilizados para os processos de *deploy*, CI/CD, etc.

### Tasks: 
- [x] Docker NodeTs para o *Backend*;

### Critérios de aceitação

- [x] Ambiente de configuração atualizado do ambiente de registros;
- [x] Documentação sobre o uso dos mesmos
