### ISSUE TITLE
HOTFIX - Retorno de Dados no Cadastro

### ISSUE THREAD

**Issue by Neitan2001** [fga-eps-mds/2021.1-Pro-Especies-Docs#116]
## Descrição da Issue
Retornar os dados de cadastro do usuário ao concluir o cadastro, tirando a senha por motivos de segurança.

### Tasks: 
- [ ] Retornar os dados de Cadastro;

### Critérios de aceitação
- [ ] Retornar os dados cadastrados;
- [ ] Não retornar a senha;
