### ISSUE TITLE
Criação da primeira versão do protótipo de alta fidelidade

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#119]
## Descrição da Issue
Criação do protótipo de alta fidelidade.

### Tasks: 
- [x] Criar todas as telas do protótipo de alta fidelidade.

### Critérios de aceitação
- [x] Seguir a identidade visual do app;
- [x] Aprovado pelo cliente.
