### ISSUE TITLE
Criação do Documento de Políticas de Repositório

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#12]
## Descrição da Issue
Criar o documento de políticas de repositório, definindo o template de _branches_, _commits_, _pull requests_ e _issues_.

### Tasks: 
- [x] Criar o documento com todos os templates;
- [x] Adicionar no gh-pages.

### Critérios de aceitação
- [x] Estar tudo bem detalhado;
- [x] Estar no gh-pages.
