### ISSUE TITLE
Preparação do Dojo de React Native

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#120]
## Descrição da Issue
Criar dojo de react native para ser aplicado no começo da próxima sprint.

### Tasks: 
- [x] Estudar react native com typescript;
- [x] Documentar principais partes sobre a tecnologia
- [x] Preparar dojo para o time que aborde os pontos principais.

### Critérios de aceitação
- [x] Preparação do dojo documentada;
- [x] Data do dojo marcada.
