### ISSUE TITLE
E03US04 - Eu como usuário, desejo filtrar os peixes afim de encontrar o peixe com mais facilidade.

### ISSUE THREAD

**Issue by PhRezende-eng** [fga-eps-mds/2021.1-Pro-Especies-Docs#121]
## Descrição da Issue
Nesta issue iremos filtrar a lista de peixes.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] FIltrar os peixes
- [x] FIltrar os peixes por mais de um atributo

### Critérios de aceitação

- [x] Ser possível filtrar os Peixes utilizando todos os atributos
- [x] Ser possível filtrar por + de 1 atributo ao mesmo tempo
