### ISSUE TITLE
Documentar Fechamento da Sprint 2 e Abertura da Sprint 3

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#122]
## Descrição da Issue
Documentar o fechamento da *sprint* 2 e a abertura da *sprint* 3.

### Tasks: 
- [ ] Documentar o fechamento da *sprint* 2;
- [ ] Documentar a abertura da *sprint* 3;
- [ ] Adicionar no gh-pages.

### Critérios de aceitação
- [ ] Estar tudo documentado no gh-pages.
