### ISSUE TITLE
Estudar plataformas para fazer deploy dos serviços

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#124]
## Descrição da Issue
Estudar plataformas que possibilitem o deploy dos serviços de forma gratuita. Será necessário fazer deploy de 2 ambientes por serviço, um para homologação e um para distribuição. Atualmente serão necessários 6 ambientes.

### Tasks: 
- [x] Pesquisar plataformas para deploy
- [x] Pesquisar formas de fazer deploy na plataforma selecionada

### Critérios de aceitação
- [x] Plataforma ser gratuita
- [x] Plataforma aceitar o deploy dos 6 ambientes sem alterar o plano de pagamento

**Comment by iurisevero** [comment]
Após olhar alguns sites de review sobre os provedores, a melhor escolha parece ser o [Heroku](https://www.heroku.com)
* [GeekFlare](https://geekflare.com/nodejs-hosting-platform/)
* [CodeInWp](https://www.codeinwp.com/blog/best-nodejs-hosting/)
* [Geshan](https://geshan.com.np/blog/2021/01/free-nodejs-hosting/)

A partir da estimativa disponibilizada no site do Heroku, o deploy da aplicação para o período do semestre ficaria gratuíta.

[Estimativa de deploy no Heroku](https://github.com/fga-eps-mds/2021.1-Pro-Especies-Docs/files/7206888/estimate-pro-especies-heroku.pdf)

É importante ressaltar que a estimativa foi feita utilizando os serviços gratuitos do heroku que não são recomendados para um produto de médio e grande porte, nem para uma deploy definitivo de produção.

**Comment by iurisevero** [comment]
Alguns tutoriais de como fazer deploy no Heroku que achei interessante:
* [How to deploy your Node.js / MongoDB app to the web, using Heroku](https://medium.com/make-school/how-to-deploy-your-node-js-mongodb-app-to-the-web-using-heroku-63d4bccf2675)
* [CI/CD Com GitHub Actions e Heroku](https://medium.com/@wagnerricardonet/ci-cd-com-github-actions-e-heroku-a48de5be02a1) : Deploy de uma aplicação em Java, mas o texto é bem detalhado
* [Deploying Node.js App to Heroku using Github Actions](https://dev.to/nipeshkc7/deploying-node-js-app-to-heroku-using-github-actions-3k7g) : Deploy de um monolítico usando github actions
* [Deploy to Heroku](https://github.com/marketplace/actions/deploy-to-heroku): Github actions que faz deploy no Heroku a partir de arquivo ou docker
