### ISSUE TITLE
Documentar Fechamento da *Sprint* 1 e Abertura da *Sprint* 2

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#126]
## Descrição da Issue
Documentar o fechamento da *Sprint* 1 e abertura da *Sprint* 2.

### Tasks: 
- [x] Documentar o fechamento da *sprint* 1;
- [x] Documentar a abertura da *sprint* 2;
- [x] Adicionar no gh-pages.

### Critérios de aceitação
- [x] Estar tudo documentado no gh-pages.
