### ISSUE TITLE
E03US05 - Eu, como usuário, desejo poder visualizar todos os peixes da wiki a fim de facilitar o reconhecimento de espécies

### ISSUE THREAD

**Issue by Neitan2001** [fga-eps-mds/2021.1-Pro-Especies-Docs#127]
## Descrição da Issue
Criar a tela de visualização de peixes da wiki e integrar com o repositório da wiki.

### Tasks: 
- [ ] Criar a tela de visualização de todos os peixes da wiki;
- [ ] Integrar com o repositório da wiki;

### Critérios de aceitação
- [ ] Telas estarem de acordo com o protótipo de alta fidelidade;
- [ ] Repositório de UserInterface estar integrado com a da wiki;
- [ ] Integrar com as telas já criadas até então;
