### ISSUE TITLE
Realizar deploy dos serviços

### ISSUE THREAD

**Issue by pedro-prp** [fga-eps-mds/2021.1-Pro-Especies-Docs#128]
## Descrição da Issue
Realizar deploy dos serviços e criação do CI de deploy.

### Tasks: 
- [ ] Realizar deploy no Heroku
- [ ] Adição de variáveis de ambiente
- [ ] Orquestração do MongoDB
- [ ] Expansão do deploy para todos os serviços
- [ ] Construção do CD no github Actions 

### Critérios de aceitação
- [ ] Ambiente de development funcional.
- [ ] CD para deploy automatico funcional.
