### ISSUE TITLE
Criar os templates de Issue, Pull Request, Branches e Commits

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#13]
## Descrição da Issue
Criação dos templates de _Issue_, _Pull Request_, _Branches_ e _Commits_.

### Tasks: 
- [x] Criar documento de todos os templates;
- [x] Adicionar o documento no gh-pages.

### Critérios de aceitação
- [x] Estar tudo bem descrito e detalhado;
- [x] Estar no gh-pages.
