### ISSUE TITLE
Configurar Integração Continua no repositório UserInterface

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#130]
## Descrição da Issue
Configurar Integração contínua com github actions no repositório [UserInterface](https://github.com/fga-eps-mds/2021.1-Pro-Especies-UserInterface).

### Tasks: 
- [x] Criar rotina de Lint
- [x] Criar rotina de Coverage
- [x] Criar rotina de geração de release

### Critérios de aceitação
- [x] Release sendo gerada com APK como artefato
- [x] Dados do Sonarcloud sendo enviados para o repositório de documentos
