### ISSUE TITLE
BUGFIX - Modificação do projeto de bare workflow e managed workflow

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#135]
## Descrição da Issue
Mudança do workflow utilizado no projeto.

### Tasks: 
- [x] Mudar workflow do expo;
- [x] Modificar o que for necessário;
- [x] Testar todo o app após modificações.
