### ISSUE TITLE
Hotfix - Pipeline quebrando por não encontrar o arquivo de configuração

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#136]
## Descrição da Issue
Arrumar pipeline adicionando no secrets uma referencia de base64 para gerar o arquivo de configuração durante o pipeline.
### Tasks: 
- [x] Transformar o arquivo em base64;
- [x] Adicionar ao secrets a base64;
- [x] Durante o CI transforma a base64 em um arquivo.
