### ISSUE TITLE
Criar documento de Plano de Gerenciamento de Comunicação

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#14]
## Descrição da Issue
Criação do documento que descreve como será o nosso plano de comunicação durante as disciplinas de EPS/MDS.

### Tasks: 
- [x] Criar o documento com todas formas de comunicação;
- [x] Adicionar no gh-pages.

### Critérios de aceitação
- [x] Documento estar bem descrito com todas as formas de comunicação;
- [x] Documento estar presente no gh-pages.
