### ISSUE TITLE
HOTFIX - Jest Reports

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#140]
## Descrição da Issue
Atualizar os repositórios para gerarem o report de teste execution e enviarem para o sonar cloud.

### Tasks: 
- [x] Instalar a biblioteca [jest-sonar](https://www.npmjs.com/package/jest-sonar)
- [x] Atualizar o arquivo jest.config.ts
- [x] Atualizar o arquivo sonar-project.properties

### Critérios de aceitação
- [x] O sonar cloud receber o report corretamente
