### ISSUE TITLE
Atualizar relatórios do analytics com novas métricas

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#143]
## Descrição da Issue
Atualizar os relatórios de métricas das releases com as novas métricas de ````tests``` e ````test_execution_time``` 

### Tasks: 
- [x] Atualizar relatórios do [serviços de usuários](https://github.com/fga-eps-mds/2021.1-Pro-Especies-User)
- [x] Atualizar relatórios do [serviço de registros de peixes](https://github.com/fga-eps-mds/2021.1-Pro-Especies-FishLog)
- [x] Atualizar realtórios do [serviço de biblioteca de dados](https://github.com/fga-eps-mds/2021.1-Pro-Especies-FishWiki)
- [x] Atualizar relatorios do ][serviço de interface do usuário](https://github.com/fga-eps-mds/2021.1-Pro-Especies-UserInterface)

### Critérios de aceitação
- [x] Relatórios conterem todas métricas definidas para avaliação: ```'files', 'functions', 'complexity', 'comment_lines_density', 'duplicated_lines_density', 'coverage', 'ncloc', 'security_rating', 'tests', 'test_success_density', 'test_execution_time', 'reliability_rating'```
- [x] Relatórios conservarem as datas que as releases foram geradas
