### ISSUE TITLE
HOTFIX - Adicionar indicador de carregamento 

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#144]
## Descrição da Issue
Em todo componente / tela que fizer alguma requisição que pode demorar (requisições a API, consultas ao AsyncStorage etc) adicionar um loading indicator.

### Tasks: 
- [x] Fazer um levantamento de todos os lugares que são necessários adicionar o loading indicator;
- [x] Criar o estado [loading, setLoading];
- [x] Toda vez que for ocorrer alguma requisição assíncrona seta o estado como true;
- [x] Toda vez que o estado for true mostrar o loading indicator.

### Exemplo
![image](https://user-images.githubusercontent.com/46005310/139741264-a9bd9102-5f34-4b1f-8faf-b775a83e85b1.png)
