### ISSUE TITLE
HOTFIX - Correção da tela de visualização de peixes e corrigir centralização

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#145]
## Descrição da Issue
Remover aspas que são colocados a utilizar o método JSON.Stringfy, e corrigir o bug que quando alguns dos atributos está preenchido o conteúdo da tela deixar de estar centralizado.

## Tasks: 
- [x] Remover os métodos JSON.Stringfy da tela de ViewFishLog e FishWiki;
- [x] Arrumar styles para corrigir centralização dos atributos;
- [x] Adicionar atributos que não estão aparecendo
- [x] Padronizar texto de peso e tamanho com o do registro.

### Atualmente
![image](https://user-images.githubusercontent.com/46005310/139741077-08194029-0fc9-4f69-95d1-a4d78cf8ec77.png)

### Esperado
![Registro](https://user-images.githubusercontent.com/46005310/139741159-b6a8898c-5c59-41a1-b86e-dbb14e66a9e6.png)
