### ISSUE TITLE
HOTFIX - Imagens na tela de listagem de biblioteca e registros não estão aparecendo

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#148]
## Descrição da Issue
Arrumar imagens na tela de listagem de biblioteca e registro.

## Tasks: 
- [x] Verificar qual o padrão para mostrar imagens base64;
- [x] Aplicar padrão ao código;
- [x] Caso registro/ peixe da biblioteca estiver sem imagem colocar o ícone de câmera cortada.

### Capturas de tela
![image](https://user-images.githubusercontent.com/46005310/139740278-27d6d395-0d93-49ad-a007-7ac71bd3e8e4.png)
![image](https://user-images.githubusercontent.com/46005310/139740293-9300d55b-b9ab-4c4a-8941-a90346aa44ab.png)
