### ISSUE TITLE
Lean Inception - Canvas MVP

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#15]
## Descrição da Issue
Realizar uma reunião para a elaboração do CANVAS MVP, que é a última etapa do Lean Inception. CANVAS MVP é um quadro visual que auxilia a equipe a alinhar e definir as estratégias do MVP. 

### Tasks: 
- [x] Elaborar o CANVAS MVP;
- [x] Realizar a dinâmica com toda a equipe;
- [x] Documentar como foi o processo de elaboração do CANVAS MVP.

### Critérios de aceitação
- [x] No mínimo 75% da equipe estar presente para a elaboração do CANVAS MVP;
- [x] Documentar o processo e subir para o gh-pages;
- [x] Criar o CANVAS MVP de acordo com o livro e a metodologia Lean Inception.

**Comment by sudjoao** [comment]
Canvas MVP V1:
![image](https://user-images.githubusercontent.com/46005310/128863774-433eea9f-fa47-4b20-af9d-8e2511a308d1.png)
![image](https://user-images.githubusercontent.com/46005310/128863821-85134197-6587-4ca5-bca2-e53f9905b240.png)
