### ISSUE TITLE
Lean Inception -  ShowCase

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#16]
## Descrição da Issue
Realizar uma reunião para a apresentação do ShowCase para o cliente.

### Tasks: 
- [x] Realizar uma reunião para a apresentação do ShowCase;
- [x] Documentar o ShowCase;

### Critérios de aceitação
- [x] Ter, no mínimo, 75% de presença da equipe;
- [x] Documentação estar disponível no gh-pages;
- [x] Realizar o ShowCase de acordo com o livro e a metodologia Lean Inception.
