### ISSUE TITLE
HOTFIX - Arrumar Navigation na tela de registro e login

### ISSUE THREAD

**Issue by Neitan2001** [fga-eps-mds/2021.1-Pro-Especies-Docs#160]
## Descrição da Issue
Arrumar Navigation na tela de registro e login

### Tasks: 
- [x] Adicionar navigation para a Home Screen na tela de registro;
- [x] Colocar o navigation da tela de login para executar ao fechar a mensagem de sucesso;

### Critérios de aceitação

- [x] Navigation do registro arrumado;
- [x] Navigation do login arrumado;
