### ISSUE TITLE
HOTFIX - Corrigir CI e gerar Major Release

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#161]
## Descrição da Issue
Atualmente o CI só envia as informações de Lint e Coverage para o SonarCloud em um PR, o que deixa os dados defasados em relação às branchs ```devel``` e ```main```. 

### Tasks: 
- [ ] Corrigir os CI para que enviem as informações da Devel e Main para o SonarCloud
- [ ] Gerar Major release

### Critérios de aceitação
- [ ] CI funcionando corretamente
