### ISSUE TITLE
Realizar Protótipos de Baixa Fidelidade

### ISSUE THREAD

**Issue by pedro-prp** [fga-eps-mds/2021.1-Pro-Especies-Docs#17]
## Descrição da Issue
Confecção de protótipos de baixa fidelidade por parte dos MDS para levantamento de requisitos e alinhamento do grupo.

### Tasks: 
- [x] Fazer protótipos voltados para as funcionalidades do MVP;
- [x] Documentar protótipos na wiki e na issue.

### Critérios de aceitação

- [x] Ter 5 protótipos de baixa fidelidade;
- [x] Protótipos focados em funcionalidades não em design;
- [x] Protótipos com todas as funcionalidades levantadas no MVP.

**Comment by sudjoao** [comment]
Artigo sobre protótipos de baixa, média e alta fidelidade para auxiliar o desenvolvimento dessa issue:

https://medium.com/ladies-that-ux-br/prot%C3%B3tipos-baixa-m%C3%A9dia-ou-alta-fidelidade-71d897559135

**Comment by Neitan2001** [comment]
![photo4947379498802850129](https://user-images.githubusercontent.com/64803935/129262040-00cda2c5-09de-458e-9988-eb3fa3a0cc63.jpg)
![photo4947379498802850131](https://user-images.githubusercontent.com/64803935/129262059-0ff43fea-e9dc-4836-83a3-ec3c0abc3b80.jpg)

**Comment by gabrielfreitass1** [comment]
Prototipo de baixa fidelidade

![image](https://user-images.githubusercontent.com/56280085/129284870-cd069aec-5210-4755-98b7-3ae01978338f.png)

**Comment by PhRezende-eng** [comment]
![1](https://user-images.githubusercontent.com/63085711/129390716-3fe5d396-e77c-4a49-9666-aff664ecf499.jpg)
![2](https://user-images.githubusercontent.com/63085711/129390712-d084cf5a-30a6-4eb5-bae7-58d54dd5b449.jpg)

**Comment by DanielCoimbra** [comment]
Lofi Prototype
![Screenshot from 2021-08-13 16-02-37](https://user-images.githubusercontent.com/49206670/129406878-a4f92a73-e762-4529-86f4-e907f1cecee2.png)

**Comment by jvBatista** [comment]
![prototipo](https://user-images.githubusercontent.com/72669616/129413282-94aba3bd-8e85-44f9-96c8-5548b5b2bd03.png)
