### ISSUE TITLE
Definir padrão arquitetural

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#19]
## Descrição da Issue
A partir da informações levantadas para visão do produto e elaboração do MVP, definir o melhor padrão arquitetural para ser adotado.

### Tasks: 
- [x] Revisar padrões arquiturais com base nos conteúdos estudados em Desenho e Arquitetura de Software
- [x] Definir padrão a ser adotado
- [x] Documentar motivações e possível representação arquitetural

### Critérios de aceitação
Caso os critérios de aceitação já tenham sido claramente definidos pela equipe, sobretudo pelo Product Owner, acrescentá-los na forma a seguir. Caso contrário, estes devem ser adicionados em um comentário pelo PO.

- [ ] Motivações bem definidas
- [ ] Documento revisado pelo grupo de EPSs

**Comment by iurisevero** [comment]
A arquitetura adotada para realização do projeto será a de [Microsserviços](https://microservices.io/patterns/microservices.html), conforme foi definido pela matéria.

A partir do MVP elaborado no _Lean Inception_ é possível definir três serviços principais utilizando a [Decomposição por Capacidade de Negócios](https://microservices.io/patterns/decomposition/decompose-by-business-capability.html):
1. Autenticação e Manutenção do usuário
2. Manutenção de relatório
3. Manutenção da biblioteca de dados (wiki)

Cada serviço terá uma _API REST_ que será o caminho pelo qual a Interface de Usuário ira comunicar com eles.
Os dados serão salvos em bancos de dados conforme definido no padrão [Banco de Dados por Serviço](https://microservices.io/patterns/data/database-per-service.html).

Como inicialmente são poucos serviços com baixa complexidade, eu não vejo necessidade de utilizar um [APIGateway](https://microservices.io/patterns/apigateway.html) e acredito que os bancos não terão muitos relacionamentos a ponto de ser necessário adotar o padrão [SAGA](https://microservices.io/patterns/data/saga.html).

Um rascunho inicial da Representação Arquitetural seria a seguinte:
![rascunho_arquitetura](https://user-images.githubusercontent.com/42645264/129642444-bfa3c702-8823-4bc6-a603-43ddfed4f2fc.jpg)

@lucasfcm9 , @sudjoao , @pedro-prp , o que acham?

P.S. : Tem um rabisco no canto da imagem falando sobre o uso do padrão para Singleton para guardar os dados do usuário após fazer uma requisição no front. Isso é algo que eu fiz em outro projeto e acredito que traria muito benefício para esse aqui, no entanto, é algo para ser discutido em outra issue.

**Comment by sudjoao** [comment]
Achei muito interessante como ficou esse rascunho da arquitetura, e muito ilustrativo também kkkk, essa Decomposição por Capacidade de Negócios fez muito sentido para mim. Realmente essa questão do singleton seria algo de se discutir, ainda mais em flutter acho que daria muito bem para aplicar. Só fico em dúvida sobre a questão do banco de dados para a biblioteca, como nesse MVP iremos apenas consumir um serviço externo, não seria melhor deixar essa questão para depois?

**Comment by sudjoao** [comment]
> A arquitetura adotada para realização do projeto será a de [Microsserviços](https://microservices.io/patterns/microservices.html), conforme foi definido pela matéria.
> 
> A partir do MVP elaborado no _Lean Inception_ é possível definir três serviços principais utilizando a [Decomposição por Capacidade de Negócios](https://microservices.io/patterns/decomposition/decompose-by-business-capability.html):
> 
> 1. Autenticação e Manutenção do usuário
> 2. Manutenção de relatório
> 3. Manutenção da biblioteca de dados (wiki)
> 
> Cada serviço terá uma _API REST_ que será o caminho pelo qual a Interface de Usuário ira comunicar com eles.
> Os dados serão salvos em bancos de dados conforme definido no padrão [Banco de Dados por Serviço](https://microservices.io/patterns/data/database-per-service.html).
> 
> Como inicialmente são poucos serviços com baixa complexidade, eu não vejo necessidade de utilizar um [APIGateway](https://microservices.io/patterns/apigateway.html) e acredito que os bancos não terão muitos relacionamentos a ponto de ser necessário adotar o padrão [SAGA](https://microservices.io/patterns/data/saga.html).
> 
> Um rascunho inicial da Representação Arquitetural seria a seguinte:
> ![rascunho_arquitetura](https://user-images.githubusercontent.com/42645264/129642444-bfa3c702-8823-4bc6-a603-43ddfed4f2fc.jpg)
> 
> @lucasfcm9 , @sudjoao , @pedro-prp , o que acham?
> 
> P.S. : Tem um rabisco no canto da imagem falando sobre o uso do padrão para Singleton para guardar os dados do usuário após fazer uma requisição no front. Isso é algo que eu fiz em outro projeto e acredito que traria muito benefício para esse aqui, no entanto, é algo para ser discutido em outra issue.

Achei muito interessante como ficou esse rascunho da arquitetura, e muito ilustrativo também kkkk, essa Decomposição por Capacidade de Negócios fez muito sentido para mim. Realmente essa questão do singleton seria algo de se discutir, ainda mais em flutter acho que daria muito bem para aplicar. Só fico em dúvida sobre a questão do banco de dados para a biblioteca, como nesse MVP iremos apenas consumir um serviço externo, não seria melhor deixar essa questão para depois?

**Comment by iurisevero** [comment]
> > A arquitetura adotada para realização do projeto será a de [Microsserviços](https://microservices.io/patterns/microservices.html), conforme foi definido pela matéria.
> > A partir do MVP elaborado no _Lean Inception_ é possível definir três serviços principais utilizando a [Decomposição por Capacidade de Negócios](https://microservices.io/patterns/decomposition/decompose-by-business-capability.html):
> > 
> > 1. Autenticação e Manutenção do usuário
> > 2. Manutenção de relatório
> > 3. Manutenção da biblioteca de dados (wiki)
> > 
> > Cada serviço terá uma _API REST_ que será o caminho pelo qual a Interface de Usuário ira comunicar com eles.
> > Os dados serão salvos em bancos de dados conforme definido no padrão [Banco de Dados por Serviço](https://microservices.io/patterns/data/database-per-service.html).
> > Como inicialmente são poucos serviços com baixa complexidade, eu não vejo necessidade de utilizar um [APIGateway](https://microservices.io/patterns/apigateway.html) e acredito que os bancos não terão muitos relacionamentos a ponto de ser necessário adotar o padrão [SAGA](https://microservices.io/patterns/data/saga.html).
> > Um rascunho inicial da Representação Arquitetural seria a seguinte:
> > ![rascunho_arquitetura](https://user-images.githubusercontent.com/42645264/129642444-bfa3c702-8823-4bc6-a603-43ddfed4f2fc.jpg)
> > @lucasfcm9 , @sudjoao , @pedro-prp , o que acham?
> > P.S. : Tem um rabisco no canto da imagem falando sobre o uso do padrão para Singleton para guardar os dados do usuário após fazer uma requisição no front. Isso é algo que eu fiz em outro projeto e acredito que traria muito benefício para esse aqui, no entanto, é algo para ser discutido em outra issue.
> 
> Achei muito interessante como ficou esse rascunho da arquitetura, e muito ilustrativo também kkkk, essa Decomposição por Capacidade de Negócios fez muito sentido para mim. Realmente essa questão do singleton seria algo de se discutir, ainda mais em flutter acho que daria muito bem para aplicar. Só fico em dúvida sobre a questão do banco de dados para a biblioteca, como nesse MVP iremos apenas consumir um serviço externo, não seria melhor deixar essa questão para depois?

Concordo que daria para deixar para depois do MVP, quando a gente já tiver dados suficientes dos relatórios para montar nosso próprio banco, mas acho que podemos discutir melhor no planning sábado. Talvez, popular nosso banco com os dados do fishbase também seja uma opção.

**Comment by sudjoao** [comment]
Beleza, sábado discutimos melhor isso então.

**Comment by lucasfcm9** [comment]
> A arquitetura adotada para realização do projeto será a de [Microsserviços](https://microservices.io/patterns/microservices.html), conforme foi definido pela matéria.
> 
> A partir do MVP elaborado no _Lean Inception_ é possível definir três serviços principais utilizando a [Decomposição por Capacidade de Negócios](https://microservices.io/patterns/decomposition/decompose-by-business-capability.html):
> 
> 1. Autenticação e Manutenção do usuário
> 2. Manutenção de relatório
> 3. Manutenção da biblioteca de dados (wiki)
> 
> Cada serviço terá uma _API REST_ que será o caminho pelo qual a Interface de Usuário ira comunicar com eles.
> Os dados serão salvos em bancos de dados conforme definido no padrão [Banco de Dados por Serviço](https://microservices.io/patterns/data/database-per-service.html).
> 
> Como inicialmente são poucos serviços com baixa complexidade, eu não vejo necessidade de utilizar um [APIGateway](https://microservices.io/patterns/apigateway.html) e acredito que os bancos não terão muitos relacionamentos a ponto de ser necessário adotar o padrão [SAGA](https://microservices.io/patterns/data/saga.html).
> 
> Um rascunho inicial da Representação Arquitetural seria a seguinte:
> ![rascunho_arquitetura](https://user-images.githubusercontent.com/42645264/129642444-bfa3c702-8823-4bc6-a603-43ddfed4f2fc.jpg)
> 
> @lucasfcm9 , @sudjoao , @pedro-prp , o que acham?
> 
> P.S. : Tem um rabisco no canto da imagem falando sobre o uso do padrão para Singleton para guardar os dados do usuário após fazer uma requisição no front. Isso é algo que eu fiz em outro projeto e acredito que traria muito benefício para esse aqui, no entanto, é algo para ser discutido em outra issue.

Gostei bastante da representação arquitetural. Concordo, acho melhor discutirmos sábado. Mas parabéns, Iuri, ficou muito bom!

**Comment by iurisevero** [comment]
Nesse caso, vou fechar essa issue e começar a versão do diagrama de representação arquitetural.
