### ISSUE TITLE
 Lean Inception - Agenda burn-up

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#2]
## Descrição da Issue
Criação da Agenda burn-up, a agenda que facilitará o gerenciamento de tempo e escopo de uma Lean Inception.
### Tasks: 
- [x] Criação de post-its para cada atividade;
- [x] Criação do gráfico Tempo x Atividades;
- [x] Explicação da Agenda para os membros ativos e stakeholders.

### Critérios de aceitação
- [x] Agenda validada por todos os membros ativos e stakeholders.

**Comment by sudjoao** [comment]
A agenda inicialmente foi pensada em 4 encontros, onde as atividades seriam:
- 1º Encontro: Kick-off, Visão do Produto, O Produto É  -Não É - Faz - Não Faz e Objetivos do produto;
- 2º Encontro: Personas, Jornadas de usuário e Brainstorming de Funcionalidades;
- 3º Encontro: Revisão Técnica, de negócio e de UX e Sequenciador
- 4º Encontro: Canvas MVP e monagem do Showcase.

**Comment by sudjoao** [comment]
Como o primeiro dia se tratou de o primeiro momento do grupo focado do Lean, acabou levando mais tempo que o esperado, por esse motivo a agenda foi alterada para:
* 1º Encontro: Kick-off, Visão do Produto, O Produto É -Não É - Faz - Não Faz;
* 2º Encontro: Objetivos do produto, Personas, e Brainstorming de Funcionalidades;
* 3º Encontro: Revisão Técnica, de negócio e de UX e Sequenciador,
* 4º Encontro: Jornadas de usuário e Canvas MVP.
* Montagem do Show Case: Assíncrona
