### ISSUE TITLE
Dockerizar ambientes de desenvolvimento

### ISSUE THREAD

**Issue by pedro-prp** [fga-eps-mds/2021.1-Pro-Especies-Docs#20]
## Descrição da Issue
Será necessário a Dockerização dos ambientes de desenvolvimento, afim que o time possa ter mais conforto no desenvolvimento. Além de posteriormente seram utilizados para os processos de deploy, CI/CD e etc.

### Tasks: 
- [x] Docker NodeTs para o Backend
- [x] Docker Python para o WebCrawler(fishbase)
- [x] Pesquisar sobre a Dockerização Flutter
- [x] Docker Flutter para o Frontend.

### Critérios de aceitação

- [x] Dockerização dos ambientes
- [x] Documentação sobre o uso dos mesmos
