### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#21]
## Descrição da Issue
Criação do modelo inicial do Product Backlog.

### Tasks:
- [x] Leitura do livro Product Backlog Building;
- [x] Criação do canva para o Product Backlog;
- [x] Explicação do product backlog building para o grupo.

### Critérios de aceitação
- [x] Metodologia para confecção do Product Backlog ser baseado no livro PBB;
- [x] Reuniões para confecção do Canvas do PBB marcadas.

**Comment by sudjoao** [comment]
Mural com o Canvas do PBB criado e dias para a dinâmica marcados.
![image](https://user-images.githubusercontent.com/46005310/129460670-14b11f7a-fb1d-48a5-be28-183e2f846de8.png)
