### ISSUE TITLE
Protótipos de Baixa Fidelidade

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#22]
## Descrição da Issue
Confecção de protótipos de baixa fidelidade para levantamento de requisitos e alinhamento do grupo.

### Tasks: 
- [ ] Fazer protótipos voltados para as funcionalidades do MVP;
- [ ] Documentar protótipos na wiki e na issue.

### Critérios de aceitação

- [ ] Ter 5 protótipos de baixa fidelidade;
- [ ] Protótipos focados em funcionalidades não em design;
- [ ] Protótipos com todas as funcionalidades levantadas no MVP.

**Comment by sudjoao** [comment]
Artigo sobre protótipos de baixa, média e alta fidelidade para auxiliar o desenvolvimento dessa issue:
- https://medium.com/ladies-that-ux-br/prot%C3%B3tipos-baixa-m%C3%A9dia-ou-alta-fidelidade-71d897559135
