### ISSUE TITLE
Criar diagrama de Gantt

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#24]
## Descrição da Issue
Criação de um gráfico de Gantt.

### Tasks: 
- [x] Criar o gráfico de Gantt com as datas e duração de cada atividade.

### Critérios de aceitação
- [x] Criar o gráfico e documentar no gh-pages;
- [x] Validar com o grupo.
