### ISSUE TITLE
Elaborar o Documento de Visão

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#25]
## Descrição da Issue
Criar o documento de visão de acordo com as regras estabelecidas pela IBM. O documento de visão deve seguir o [template](https://www.ibm.com/support/knowledgecenter/pt-br/SSWMEQ_4.0.6/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html) utilizado no treinamento.

### Tasks: 
- [x] Elaborar o documento de visão;
- [x] Adicionar o documento no gh-pages.

### Critérios de aceitação
- [x] Todos os tópicos estarem completos;
- [x] Estar seguindo o template disponibilizado pela IBM;
- [x] Estar disponível no gh-pages;
- [x] Ser validado pelos EPS.

**Comment by iurisevero** [comment]
Referências para o documento de visão:
https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/vision-document/
https://fga-eps-mds.github.io/2019.1-Aix/projeto/2019/03/29/documento-de-visao/
https://fga-eps-mds.github.io/2019.1-ADA/#/docs/product/vision_document
https://botlino.github.io/docs/doc-visao
https://fga-eps-mds.github.io/2018.2-Kalkuli/docs/docVisao

**Comment by Neitan2001** [comment]
A divisão dos tópicos do documento de visão foi feita por discord entre os alunos de MDS de acordo com os tópicos listados pelo IBM. A divisão ficou da seguinte forma:
Tópico 1 - Natan
Tópico 2 - Natan
Tópico 3 - Daniel
Tópico 4 - Batista
Tópico 5 - Freitas
Tópico 6 - Batista
Tópico 8 - Paulo
Tópico 9 - Paulo
Tópico 10 - Paulo
Os tópicos 7 e 11 foram excluídos por não encaixarem no contexto do projeto
