### ISSUE TITLE
Elaborar o Documento de Arquitetura

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#26]
## Descrição da Issue
Criar o documento de arquitetura de acordo o template utilizado e ensinado no treinamento.
### Tasks: 
- [x] Elaborar o documento de arquitetura;
- [x] Adicionar o documento no gh-pages.

### Critérios de aceitação
- [x] Todos os tópicos estarem completos;
- [x] Estar seguindo o template ensinado no treinamento;
- [x] Estar disponível no gh-pages;
- [x] Ser validado pelos EPS.

**Comment by sudjoao** [comment]
https://unbarqdsw.github.io/2020.1_G13_iGado/#/

**Comment by iurisevero** [comment]
A primeira versão do Diagrama de Representação Arquitetural baseado no MVP ficou assim:
![representacao-arquitetural](https://user-images.githubusercontent.com/42645264/130293941-2f4f439c-bf17-4e73-b641-066880e508ab.png)

**Comment by sudjoao** [comment]
https://github.com/fga-eps-mds/2020.2-Lend.it
