### ISSUE TITLE
Confecção do Protótipo de Média Fidelidade

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#27]
## Descrição da Issue
Utilizar os protótipos de baixa fidelidade feitos para o desenvolvimento do protótipo de média fidelidade.

### Tasks: 
- [x] Criação de Protótipo de média fidelidade com as funcionalidades levantadas do lean inception.

### Critérios de aceitação

- [x] Protótipo em conformidade com as funcionalidades do lean inception.
- [x] Protótipo seguindo as ideias levantadas nos protótipos de baixa fidelidade.
- [x] Protótipo validado pelo grupo.

**Comment by sudjoao** [comment]
Segue a 1ª versão do protótipo de média fidelidade feito pelo grupo.
![image](https://user-images.githubusercontent.com/46005310/129461012-f5e0baa6-553a-4933-9dbc-92bab7e619e3.png)
