### ISSUE TITLE
Visão do Produto

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#3]
## Descrição da Issue
Com os dados passados pelo cliente sobre a ideia do produto, levantar, em pequenos grupos, a visão do produto.
### Tasks: 
- [x] Organização da dinâmica;
- [x] Cada grupo definir algumas lacunas do template de visão de produto;
- [x] Unir as lacunas e formar uma frase completa que define a visão do produto.

### Critérios de aceitação
- [x] Participação do cliente;
- [x] Participação de pelo menos 50% do time;
- [x] Visão do produto definida e aprovada pelo time.

**Comment by sudjoao** [comment]
**Visão do produto** 
Para pesquisadores, cujo problema é a falta de tempo/recurso para ir atrás dos dados dessas espécies em risco, que podem se encontrar em áreas de difícil acesso e para pescadores, cujo problema é a falta de motivação para relatar espécies sensíveis a extinção em localidades de difícil acesso, o Pró-especies Peixes (nome temporário), é um Aplicativo Mobile, que facilita o acesso dos dados das especies até o pesquisador, ondem os pescadores mapeam e catalogam-as, diferente da Pesca+ e iNaturalist, o nosso produto tem praticidade de acesso a informação, é acessível e focado na preservação das espécies.
