### ISSUE TITLE
Criação do Backlog do Produto V1

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#31]
## Descrição da Issue
Utilizando a metodologia Product Backlog Building, criar a primeira versão do Product Backlog.

### Tasks: 
- [ ] Organização da aplicação do Product Backlog Building;
- [ ] Levantamento dos problemas;
- [ ] Levantamento das expectativas;
- [ ] Levantamento das personas;
- [ ] Levantamento das features;
- [ ] Levantamento dos Product Backlog Items(PBIs);
- [ ] Criação das Histórias de Usuário.

### Critérios de aceitação
- [ ] Participação de pelo menos 75% do grupo;
- [ ] Utilização de informações levantadas no lean inception;
- [ ] Apresentada para o cliente;
- [ ] PBB Canvas preenchido completamente.

**Comment by sudjoao** [comment]
PBB Canvas
![PBB](https://user-images.githubusercontent.com/46005310/130338937-01d68698-cf52-404c-ab91-615bd5627423.png)

**Comment by sudjoao** [comment]
Backlog V1
![image](https://user-images.githubusercontent.com/46005310/130338945-4069d3ea-0d02-4f7b-8918-60f82123f574.png)
