### ISSUE TITLE
Documentar Planejamento Sprint 1

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#32]
## Descrição da Issue
Documentar o planejamento da Sprint 1.

### Tasks: 
- [x] Documentar o planejamento da sprint 1;
- [x] Adicionar no gh-pages;

### Critérios de aceitação
- [x] Validar o planejamento da sprint 1;
- [x] Estar documento no gh-pages;
