### ISSUE TITLE
Plano de Gerenciamento de Custos

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#34]
## Descrição da Issue
Criação da versão inicial do Plano de Gerenciamento de Custos.

### Tasks: 
- [x] Levantamento de modelo do Plano de Gerenciamento de Custos;
- [x] Levantamento de dados para o preenchimento;
- [x] Preenchimento do modelo com as informações que foram levantadas.

### Critérios de aceitação
- [x] Validar com o time;
- [x] Apresentar para o cliente;
- [x] Disponibilizar na wiki.
