### ISSUE TITLE
O produto é não é faz não faz

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#4]
## Descrição da Issue
Definir o que o produto vai fazer ou não utilizando a dinâmica É - Não é - Faz - Não faz.
### Tasks: 
- [x] Organização da dinâmica;
- [x] Dividir o time em 2 grupos, onde um definirá o É - Faz e outro Não é - Não Faz
- [x] Pegar o que foi definido e agrupá-los em clusters.

### Critérios de aceitação
- [x] Participação do cliente;
- [x] Pelo menos 50% do time participando;
- [x] Definição do template aprovada pelo cliente e time.

**Comment by sudjoao** [comment]
**Resultado da dinâmica**
![image](https://user-images.githubusercontent.com/46005310/128760141-d6834ebc-69d4-47cd-8ba0-c8dbfe015da8.png)

![image](https://user-images.githubusercontent.com/46005310/128760084-394c1a17-d0e6-467f-a820-73ca3136dba5.png)
