### ISSUE TITLE
Integração e configuração do banco de dados no Backend

### ISSUE THREAD

**Issue by pedro-prp** [fga-eps-mds/2021.1-Pro-Especies-Docs#40]
## Descrição da Issue
Integração do backend em Node Express com o banco de dados mongodb.

### Tasks: 
- [x] Configuração do Docker-compose mongodb
- [x] Criação da estrutura de Models
- [x] Estudo sobre uso de ".envs"

### Critérios de aceitação
- [x] Bancos de dados funcional e integrado com Docker-compose
- [x] Contextualização com o time sobre a configuração do banco de dados
