### ISSUE TITLE
Integração e configuração do banco de dados no Crawler

### ISSUE THREAD

**Issue by pedro-prp** [fga-eps-mds/2021.1-Pro-Especies-Docs#41]
## Descrição da Issue
Integração do crawler em Python Flask com o banco de dados mongodb.

### Tasks: 
- [x] Configuração do Docker-compose mongodb
- [x] Estudo sobre uso de ".envs"

### Critérios de aceitação
- [x] Bancos de dados funcional e integrado com Docker-compose
- [x] Contextualização com o time sobre a configuração do banco de dados
