### ISSUE TITLE
Configuração do Lint workflow do serviços

### ISSUE THREAD

**Issue by pedro-prp** [fga-eps-mds/2021.1-Pro-Especies-Docs#42]
## Descrição da Issue
Criação do CI para realizar Lint dos serviços.

### Tasks: 
- [x] Definir Lint a ser utilizado no Backend
- [x] Criação do Lint CI para o Backend

### Critérios de aceitação
- [x] Lint do Backend configurado e funcional
