### ISSUE TITLE
E01US01 - Eu, como usuário, desejo poder me cadastrar na plataforma para poder realizar registro e coleta de dados sobre peixes

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#43]
## Descrição da Issue
Desenvolvimento da funcionalidade de cadastro no backend.

### Tasks: 
- [x] Criação da model de pescador;
- [x] Criação da model de pesquisador;
- [x] Criação do método para salvar os dados no banco;
- [x] Criptografar senha do usuário;
- [x] Criação da rota para envio dos dados.

### Critérios de aceitação

- [x] Ser possível cadastrar um usuário utilizando a rota do backend;
- [x] Dados do usuário serem salvos no banco;
- [x] Senha estar criptografada.
