### ISSUE TITLE
Documentar abertura da Sprint 0 e revisar os artefatos

### ISSUE THREAD

**Issue by ghost** [fga-eps-mds/2021.1-Pro-Especies-Docs#44]
## Descrição da Issue
Documentar abertura da *sprint* 0 e revisar todos os artefatos até agora criados.

### Tasks: 
- [x] Documentar a abertura da *sprint* 0;
- [x] Adicionar no gh-pages;
- [x] Revisar os artefatos.

### Critérios de aceitação
- [x] Validar com a equipe;
- [x] Tudo estar documentado na nossa wiki.
