### ISSUE TITLE
E01US02 - Eu, como usuário, desejo acessar minha conta na plataforma para poder realizar registro e coleta de dados sobre peixes

### ISSUE THREAD

**Issue by PhRezende-eng** [fga-eps-mds/2021.1-Pro-Especies-Docs#45]
## Descrição da Issue
Desenvolvimento da funcionalidade de login no backend.

### Tasks: 
- [x] Crição do método de verificação de conta
- [x] Criação da rota para envio dos dados 

### Critérios de aceitação
- [x] Ser possível verificar conta utilizando rota do backend
- [x] Retornar mensagem de sucesso/error
