### ISSUE TITLE
E01US03 - Eu, como usuário, desejo ser autenticado pelo aplicativo para poder realizar registro e coleta de dados sobre peixes

### ISSUE THREAD

**Issue by PhRezende-eng** [fga-eps-mds/2021.1-Pro-Especies-Docs#46]
## Descrição da Issue
Desenvolvimento do método para retornar token de acesso

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Criação do método de token acesso

### Critérios de aceitação
- [x] Criação de token se os dados estiverem corretos
- [x] Retorno do token para frontend
