### ISSUE TITLE
Configuração do SonarQube no Frontend

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#47]
## Descrição da Issue
Criar estrutura inicial do frontend e configuração do SonarQube.
### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Criar estrutura inicial do frontend;
- [x] Configurar o plugin do Sonar-Flutter;
- [ ] Integrar plugin com o SonarCloud.

### Critérios de aceitação
- [ ] Conseguir tirar as métricas esperadas pelo professor usando  o plugin;
- [x] Ser possível visualizar as métricas no SonarCloud.

**Comment by sudjoao** [comment]
Plugin no ambiente de desenvolvimento configurado, agora basta configurar para o CI
![Captura de tela de 2021-09-04 13-53-05](https://user-images.githubusercontent.com/46005310/132102376-563f9742-fa1f-4b29-8c03-a082fda33232.png)
