### ISSUE TITLE
E03US04 - Eu, como usuário, desejo poder armazenar dados do fishbase no banco de dados para conseguir informações dos peixes de maneira mais rápida

### ISSUE THREAD

**Issue by jvBatista** [fga-eps-mds/2021.1-Pro-Especies-Docs#48]
## Descrição da Issue
Desenvolvimento da funcionalidade de atualização do banco de dados da wiki.

### Tasks: 
- [ ] Criação do método de atualização do banco;
- [ ] Criação de rota para envio de dados.

### Critérios de aceitação
- [ ] Ser possível atualizar os dados do banco utilizando a rota do backend;
- [ ] Ser possível visualizar todos os peixes salvos no banco.
