### ISSUE TITLE
E03US03 - Eu, como usuário, desejo poder filtrar os peixes cadastrados de acordo com determinado atributo

### ISSUE THREAD

**Issue by jvBatista** [fga-eps-mds/2021.1-Pro-Especies-Docs#49]
## Descrição da Issue
Desenvolvimento da funcionalidade de filtro dos peixes da wiki.

### Tasks: 
- [ ] Criação de método de filtrar dados por determinado atributo;
- [ ] Criação da rota para envio de dados.

### Critérios de aceitação
- [ ] Ser possível filtrar dados básicos;
- [ ] Ser possível visualizar apenas os peixes que possuem aqueles dados.
