### ISSUE TITLE
Objetivos do Produto

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#5]
## Descrição da Issue
Definir os objetivos do produto, onde cada participante do grupo levantará quais são os 3 objetivos principais do produto.
### Tasks: 
- [x] Organizar a dinâmica;
- [x] Pedir para cada pessoa do grupo levantar três objetivos;
- [x] Agrupar os objetivos levantados em clusters de similaridade.

### Critérios de aceitação
- [x] Participação do cliente;
- [x] Participação de pelo 50% do time;
- [x] Definição dos clusters dos objetivos do projeto.

**Comment by sudjoao** [comment]
**A dinâmica resultou nestes objetivos:**
![image](https://user-images.githubusercontent.com/46005310/128768456-fa0cf637-522b-4df6-be96-9862461e1ce4.png)
