### ISSUE TITLE
Criar Diagrama de Classes

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#51]
## Descrição da Issue
Criar o Diagrama de Classes referente aos serviços já definidos na representação arquitetural.

### Tasks: 
- [ ] Criar classe de Usuários
- [ ] Criar classe de Relatório 
- [ ] Criar classe da Biblioteca de Dados
- [ ] Adicionar diagrama ao documento de arquitetura/

### Critérios de aceitação
- [ ] Diagramas revisados pelo time de EPS
- [ ] Explicar diagramas para o time de MDS
- [ ] Tabela de versão do documento atualizada

**Comment by iurisevero** [comment]
Rascunho inicial dos diagramas
![image](https://user-images.githubusercontent.com/42645264/130658784-cd29531a-d0ce-43b6-840c-bf9d49e7386e.png)
