### ISSUE TITLE
E03US01 - Eu, como usuário, desejo obter dados do fishbase para obter mais informações sobre os peixes

### ISSUE THREAD

**Issue by jvBatista** [fga-eps-mds/2021.1-Pro-Especies-Docs#52]
## Descrição da Issue
Desenvolver o crawler da aplicação para obter dados do fishbase

### Tasks: 
- [ ] Criação do crawler da wiki;
- [ ] Conversão dos dados do crawler para um arquivo json;

### Critérios de aceitação
- [ ] Gerar arquivo json contendo os dados dos peixes.
