### ISSUE TITLE
Documentar os léxicos

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#53]
## Descrição da Issue
Documentar os léxicos, que tem o objetivo de  elaborar os  modelos capazes de representar características ou comportamentos de um software.

### Tasks: 
- [ ] Documentar/Criar os léxicos (verbo, estado e objeto);
- [ ] Definir como será organizado;
- [ ] Adicionar na gh-pages;

### Critérios de aceitação
- [ ] Ter todos os léxicos que englobam todos os requisitos levantados;
- [ ] Estar documentado no gh-pages;
- [ ] Validar com o P.O.
