### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#6]
## Descrição da Issue
Definição de público alvo do aplicativo utilizando o conceito de personas.

### Tasks: 
- [x] Organizar a dinâmica;
- [x] Separar o time em 3 grupos e cada 1 levantar 1 persona;
- [x] Apresentar as personas levantadas para o grupo.

### Critérios de aceitação
- [x] Participação do Cliente;
- [x] Participação de no mínimo 50% do grupo;
- [x] Personas condizentes ao produto.

**Comment by sudjoao** [comment]
Personas definidas pelo grupo:
* Persona 1
![image](https://user-images.githubusercontent.com/46005310/128770000-b7e11b35-c2f5-461b-98c7-61beaa2bfee4.png)
* Persona 2
![image](https://user-images.githubusercontent.com/46005310/128770065-fa2e7a84-92ba-4fa1-95bf-8aa739a40485.png)
* Persona 3
![image](https://user-images.githubusercontent.com/46005310/128770154-5e9c2c57-4994-47e6-bd4c-fceda73ed0c0.png)
