### ISSUE TITLE
Revisão do diagrama de Casos de Uso

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#67]
## Descrição da Issue
Revisar a necessidade e o quão coerente o diagrama de casos de uso está.

### Tasks: 
- [x] Ler documentação sobre diagrama de casos de uso;
- [x] Revisar o diagrama feito pelo grupo;

### Critérios de aceitação
- [x] Diagrama removido ou refinado de acordo com a avaliação do grupo.
