### ISSUE TITLE
Elaborar NFR

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#68]
## Descrição da Issue
Elaborar NFR para os requisitos não funcionais do projeto.

### Tasks: 
- [x] Levantar dados sobre o uso do NFR;
- [x] Verificar se realmente o NFR é necessário para o contexto do projeto;
- [ ] Criar o NFR se necessário

### Critérios de aceitação
- [x] Justificar a utilização ou não do NFR no projeto.

**Comment by sudjoao** [comment]
Após pesquisas decidimos que o NFR não era algo muito útil na metodologia atual que o grupo está utilizando.
