### ISSUE TITLE
Criação de uma tabela explicando cada licença 

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#69]
## Descrição da Issue
Criar tabela com as restrições e permissões de cada licença.

### Tasks: 
- [x] Estudar as licenças de software;
- [x] Criar tabela com as principais restrições e permissões de cada licença;
- [x] Apresentar tabela para o cliente.

### Critérios de aceitação
- [x] Tabela escrita de um jeito que o cliente possa compreender;
- [x] Tirar todas as dúvidas do cliente utilizando a tabela.

**Comment by sudjoao** [comment]
Tabela apresentada e licença definida.
