### ISSUE TITLE
Brainstorming de funcionalidades

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#7]
## Descrição da Issue
Fazer o levamento de funcionalidades baseado nos dados levantados.

### Tasks: 
- [x] Organizar dinâmica;
- [x] Levantar funcionalidades para cada objetivo;
- [x] Levantar funcionalidades para cada persona.

### Critérios de aceitação
- [x] Participação do cliente;
- [x] Participação de pelo menos 50% do time;
- [x] Levantamento de funcionalidades condizente com objetivo e personas.

**Comment by sudjoao** [comment]
Funcionalidades levantadas pelo grupo
![image](https://user-images.githubusercontent.com/46005310/128771568-7743ac2b-01f1-4bee-9eab-d64cd8a330bc.png)
