### ISSUE TITLE
HOTFIX - Imagens Quebradas na Wiki

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#70]
## Descrição da Issue
Existem algumas imagens quebradas na wiki, principalmente na parte de backlog e protótipo de baixa fidelidade, é necessário arrumar essas imagens.

### Tasks: 
- [ ] Descobrir o porquê as imagens estão quebradas;
- [ ] Arrumar as imagens.

### Critérios de aceitação
- [ ] As imagens estarem funcionando tanto no ambiente de desenvolvimento quanto no github pages.

**Comment by sudjoao** [comment]
As imagens estavam quebradas pois ao utilizar a tag *img* do html ao invés de passar o caminho relativo, utilizando *../* , basta passar o caminho da pasta direto, sem o *"../*.
