### ISSUE TITLE
HOTFIX Atualizar variáveis e segredo usados para geração de token de autenticação

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#72]
## Descrição da Issue
O token de autenticação gerado agora deve possuir os seguintes dados do usuário: id, email/telefone, senha e o booleano de admin. O segredo usado para gerar o token deve ser atualizada para uma variável de ambiente.

### Tasks: 
- [x] Atualizar dados que geram o Token de autenticação
- [x] Atualizar segredo que gera o Token de autenticação

### Critérios de aceitação
- [x] Token possui todas informações necessárias
- [x] O segredo de geração do token deve estar inacessível para pessoas de fora do projeto
