### ISSUE TITLE
E09US01 - Eu, como pescador, gostaria que meus registros sejam salvos enquanto eu não tiver conexão com a internet, para que eu possa enviá-los posteriormente uma vez que haja conexão

### ISSUE THREAD

**Issue by jvBatista** [fga-eps-mds/2021.1-Pro-Especies-Docs#75]
### Tasks: 
- [x] Criação de um alerta avisando que o usuário está sem internet;
- [x] Criação de um rascunho para salvar os dados do registro do usuário;
- [x] Criação de uma tela para acessar os rascunhos.

### Critérios de aceitação
- [x] Ser possível criar um rascunho quando estiver sem internet;
- [x] Ser possível enviar os dados posteriormente quando tiver acesso a internet;
- [x] Ser possível editar os dados de um rascunho.
