### ISSUE TITLE
Alterar nome do repositório de serviço de usuário

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#78]
## Descrição da Issue
Alterar nome do repositório e informações do repositório de serviço de usuário.
### Tasks: 
- [x] Alterar nome do repositório;
- [x] Alterar nome do docker;
- [x] Alterar nome nas configurações do projeto.

### Critérios de aceitação
- [x] Serviço continuar funcionando.
