### ISSUE TITLE
E03US03 - Eu, como usuário, desejo pesquisar peixes na wiki para ter um acesso mais fácil às informações sobre peixes específicos

### ISSUE THREAD

**Issue by DanielCoimbra** [fga-eps-mds/2021.1-Pro-Especies-Docs#79]
## Descrição da Issue
Nesta issue iremos criar a tela de wiki de peixes e fazer a busca por um peixe da wiki.

### Tasks: 
- [x] Pesquisar peixe
- [x] Fazer a tela de biblioteca
- [x] Usar o FlatLIst para scrollar os peixes

### Critérios de aceitação
- [x] Ser possível vizualizar todos os peixes cadastrados na wiki
- [x] Ser possível pesquisar por nome de peixe e espécie
- [x] Feedback caso nenhum peixe seja encontrado
- [x] Ao clicar no card de um peixe abrir a página de informação dele
