### ISSUE TITLE
Lean Inception - Revisão Técnica, de Negócio e de UX

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#8]
## Descrição da Issue
Revisar funcionalidades levantadas em nível técnico, de negócio e UX. 
### Tasks: 
- [x] Organizar dinâmica;
- [x] Fazer revisão técnica, de negócio e UX;
- [x] Utilizar a matriz de semáforo para definir as cores.

### Critérios de aceitação
- [x] Participação de pelo menos 50% do grupo;
- [x] Consegui definir o esforço, nível de negócio e UX do produto;
- [x] Definir nível de confiança de cada funcionalidade.

**Comment by sudjoao** [comment]
Revisão realizada e o resultado foi:
![image](https://user-images.githubusercontent.com/46005310/128773683-455b9e33-7109-4188-ae2e-ac96d5322811.png)

**Comment by DanielCoimbra** [comment]
Lido. Recebi agora os primeiros
