### ISSUE TITLE
E04US01 - Eu, como usuário, desejo acessar o histórico dos registros que enviei, para revistá-los e checar seus status

### ISSUE THREAD

**Issue by DanielCoimbra** [fga-eps-mds/2021.1-Pro-Especies-Docs#81]
### Tasks: 

- [x] Criação da Fishlogs Screen seguindo o protótipo
- [x] Mostrar apenas as informações disponíveis em cada registro
- [x] Mostrar indicador de carregamento enquanto a requisição para api estiver sendo feita

### Critérios de aceitação

- [x] Telas estarem seguindo o protótipo
- [x] Mostrar placeholders no lugar de informações não disponíveis (exemplo: câmera cortada no caso de não haver foto do peixe)
- [x] Mostrar Indicador de carregamento da API
