### ISSUE TITLE
Configurar lint do flutter

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#89]
## Descrição da Issue
Fazer configuração do lint do flutter para ser utilizado no CI.

### Tasks: 
- [ ] Ler sobre as libs de lint;
- [ ] Selecionar a melhor lib;
- [ ] Fazer a configuração;
- [ ] Arrumar problemas que aparecerem

### Critérios de aceitação
- [ ] Só ser possível subir o código se o lint estiver 100%.
