### ISSUE TITLE
Lean Inception - Jornada do Usuário

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2021.1-Pro-Especies-Docs#9]
## Descrição da Issue
Criação das jornadas de usuário para cada persona.
### Tasks: 
- [x] Organizar dinâmica;
- [x] Definir jornada do usuário para cada persona;
- [x] Referenciar funcionalidades presentes em cada jornada de usuário.

### Critérios de aceitação
- [x] Participação de pelo menos 50% do grupo;
- [x] Jornadas de usuários condizentes com as personas;
- [x] Funcionalidades referenciadas corretamente.

**Comment by sudjoao** [comment]
Jornadas de usuário definidas pelo grupo:
* Jornada 1
![image](https://user-images.githubusercontent.com/46005310/128862282-c9c4074d-6312-479c-b0b5-3f06b0994cde.png)

* Jornada 2
![image](https://user-images.githubusercontent.com/46005310/128862416-c872c619-1d40-462d-ae93-5f184d135408.png)

* Jornada 3
![image](https://user-images.githubusercontent.com/46005310/128862475-e56f4a6c-3e3b-4948-bee1-6fb6d14f5189.png)
