### ISSUE TITLE
Refatoração de documentos

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#90]
## Descrição da Issue
Verificar todos os documentos que serão avaliados na R1 e fazer uma refatoração caso necessário

### Tasks: 
- [x] Verificar Canvas MVP;
- [x] Verificar documento de comunicação interna e externa;
- [x] Verificar PBB Canvas e Backlog do Produto;
- [x] Verificar Documento de Arquitetura
- [x] Verificar Planilhas e Gráficos de Custo, Tempo e Risco.

### Critérios de aceitação
- [x] Utilizar alguma bibliografia para verificar se os documentos estão bons ou não e especificar nas referências do documento.

**Comment by iurisevero** [comment]
Atualização do Diagrama de Classes e dos Diagramas de Pacotes

![BackPackageDiagram](https://user-images.githubusercontent.com/42645264/132401622-948c48f0-e173-4f90-9ab5-8cfae2e2ea17.png)
![ClassDiagram](https://user-images.githubusercontent.com/42645264/132401626-8b26d31a-1379-4b46-91ac-2886f19df0ef.png)
![FrontPackageDiagram](https://user-images.githubusercontent.com/42645264/132401631-e237d334-a390-41b9-bc97-0a1860b22405.png)
