### ISSUE TITLE
Coleta de dados do sonarcloud

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2021.1-Pro-Especies-Docs#93]
## Descrição da Issue
Gerar dados de todos os serviços utilizando o sonar cloud.

### Tasks: 
- [ ] Verificar se o sonarcloud está pegando todos os dados necessários;
- [ ] Gerar json com os dados requisitados.

### Critérios de aceitação
- [ ] Dados exatamente do jeito que está especificado pelo professor.
