### ISSUE TITLE
Testes no repositório de Registros

### ISSUE THREAD

**Issue by Neitan2001** [fga-eps-mds/2021.1-Pro-Especies-Docs#95]
## Descrição da Issue
Realizar cobertura de testes no repositório de registros;

### Tasks: 
- [x] Criar testes para os métodos do repositório;

### Critérios de aceitação
- [x] Todos os testes estarem rodando;
- [x] Coverage de pelo menos 75%;
